# Generated by Django 2.2.5 on 2019-09-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAlim', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200, unique=True)),
                ('nameStore', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('descriptionAlim', models.CharField(max_length=1500, unique=True)),
                ('nutritionGrade', models.CharField(max_length=200, unique=True)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Foodsave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Products')),
            ],
        ),
    ]
