# Generated by Django 2.2.6 on 2019-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='idCategory',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='descriptionAlim',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nameAlim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutritionGrade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
