# Generated by Django 2.2.6 on 2019-11-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aliments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStore', models.CharField(max_length=200)),
                ('nameStore', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='nameStore',
        ),
        migrations.AddField(
            model_name='category',
            name='idCategory',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodsave',
            name='idUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='descriptionAlim',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nameAlim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutritionGrade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='idStore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aliments.Store'),
            preserve_default=False,
        ),
    ]
