# Generated by Django 2.2.6 on 2019-11-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0002_auto_20191123_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='idCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aliments.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='idStore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aliments.Store'),
        ),
    ]
