# Generated by Django 2.2.6 on 2019-10-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStore', models.CharField(max_length=200)),
                ('nameStore', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='category',
            name='idCategory',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='descriptionAlim',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='nameAlim',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='nameStore',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutritionGrade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='idStore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aliments.Store'),
            preserve_default=False,
        ),
    ]
