# Generated by Django 2.2.6 on 2019-10-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0003_auto_20191015_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='nameStore',
        ),
    ]
