# Generated by Django 2.2.5 on 2019-10-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0004_remove_products_namestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='foodsave',
            name='idUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aliments.User'),
            preserve_default=False,
        ),
    ]
