# Generated by Django 2.2.6 on 2019-10-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0006_auto_20191021_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descriptionAlim',
            field=models.CharField(max_length=3000),
        ),
    ]
